# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TableName(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, table_name: str=None):  # noqa: E501
        """TableName - a model defined in Swagger

        :param table_name: The table_name of this TableName.  # noqa: E501
        :type table_name: str
        """
        self.swagger_types = {
            'table_name': str
        }

        self.attribute_map = {
            'table_name': 'table name'
        }
        self._table_name = table_name

    @classmethod
    def from_dict(cls, dikt) -> 'TableName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TableName of this TableName.  # noqa: E501
        :rtype: TableName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def table_name(self) -> str:
        """Gets the table_name of this TableName.


        :return: The table_name of this TableName.
        :rtype: str
        """
        return self._table_name

    @table_name.setter
    def table_name(self, table_name: str):
        """Sets the table_name of this TableName.


        :param table_name: The table_name of this TableName.
        :type table_name: str
        """

        self._table_name = table_name
